Repository prgrms-web-devcourse-final-project/WEB1_1_PETMATZ_FE, pull requests merged in 2024-11, with the labels that each got.

#3 Setting: Theme 적용 및 루트 레이아웃 수정
  src/index.css
  src/layouts/index.tsx
  tailwind.config.js
Labels: ⚙ Setting

#6 [Style] 루트레이아웃 소폭 수정
  src/index.css
  src/layouts/index.tsx
  tailwind.config.js
Labels: 🎨 Html&css

#11 [Feat] Chat 레이아웃 작성 및 관련 유틸 함수 작성
  .github/ISSUE_TEMPLATE/기능-구현-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/버그-이슈-템플릿.md
  .github/pull_request_template.md
  package-lock.json
  package.json
  public/data/chat.json
  public/data/chatRoom.json
  src/assets/images/calendar.svg
  src/assets/images/leftArrow.svg
  src/assets/images/menuDots.svg
  src/assets/images/send.svg
  src/components/chat-detail/ChatBar.tsx
  src/components/chat-detail/ChatTopbar.tsx
  src/components/chat-detail/DateViewer.tsx
  src/components/chat-detail/MyMessage.tsx
  src/components/chat-detail/OtherMessage.tsx
  src/components/chat-detail/PostGuide.tsx
  src/components/chat-detail/index.ts
  src/components/chat/ChatRoom.tsx
  src/components/chat/ChatRoomSkeleton.tsx
  src/components/chat/index.ts
  src/components/common/Dropdown.tsx
  src/components/common/index.ts
  src/hooks/index.ts
  src/hooks/useFadeNavigate.ts
  src/layouts/index.tsx
  src/pages/Chat.tsx
  src/pages/ChatDetail.tsx
  src/pages/index.tsx
  src/router.tsx
  src/stores/useUserStore.ts
  src/types/chat.d.ts
  src/types/user.d.ts
  src/types/vite-env.d.ts
  src/utils/chat/getOtherUserForChat.ts
  src/utils/chat/getOtherUserForChatRoom.ts
  src/utils/chat/groupMesagesByDate.ts
  src/utils/chat/index.ts
  src/utils/chat/transDateForChatRoom.ts
  src/utils/index.ts
  src/utils/utcToLocalTime.ts
  vite.config.ts
Labels: ✨ Feature, 🎨 Html&css

#13 [Feat] 헤더 영역 및 바텀 Nav 영역 작성
  src/assets/images/bottom-nav/chat.svg
  src/assets/images/bottom-nav/home.svg
  src/assets/images/bottom-nav/match.svg
  src/assets/images/bottom-nav/please.svg
  src/assets/images/bottom-nav/sos.svg
  src/assets/images/header/logo.svg
  src/assets/images/header/notification.svg
  src/assets/images/header/user.svg
  src/layouts/BottomNav.tsx
  src/layouts/Header.tsx
  src/pages/Please.tsx
  src/pages/index.tsx
  src/router.tsx
  tailwind.config.js
Labels: ✨ Feature

#20 [Feat] 인트로 페이지 레이아웃 및 슬라이더 작성
  package-lock.json
  package.json
  src/assets/images/intro/arrowRight.svg
  src/assets/images/intro/atSign.svg
  src/assets/images/intro/kakaoLogo.svg
  src/assets/images/intro/largeDog.svg
  src/assets/images/intro/middleDog.svg
  src/assets/images/intro/smallDog.svg
  src/components/intro/SlideContent.tsx
  src/components/intro/SliderSection.css
  src/components/intro/SliderSection.tsx
  src/components/intro/index.ts
  src/pages/Intro.tsx
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&css

#23 [Bug] 인트로 페이지 슬라이드 위치 수정
  src/components/intro/SlideContent.tsx
  src/components/intro/SliderSection.tsx
  src/pages/Intro.tsx
Labels: 🐞 BugFix

#24 [Feat] 로그인 페이지 작성
  src/assets/images/header/back.svg
  src/assets/images/login/forward.svg
  src/hooks/index.ts
  src/hooks/useLoginForm.ts
  src/pages/Login.tsx
Labels: ✨ Feature, 🎨 Html&css

#26 [Feat] 임시 비밀번호 발급 페이지 작성
  src/assets/images/forgot-password/check.svg
  src/assets/images/forgot-password/middleSizeDog.svg
  src/components/forgot-password/Success.tsx
  src/components/forgot-password/index.tsx
  src/hooks/index.ts
  src/hooks/useForgotPasswordForm.ts
  src/pages/ForgotPassword.tsx
  src/pages/index.tsx
  src/router.tsx
Labels: ✨ Feature, 🎨 Html&css

#28 [Feat] 비밀번호 변경 페이지 작성
  src/components/forgot-password/Success.tsx
  src/hooks/index.ts
  src/hooks/useChangePasswordForm.ts
  src/pages/ChangePassword.tsx
  src/pages/ForgotPassword.tsx
  src/pages/Login.tsx
  src/pages/index.tsx
  src/router.tsx
Labels: ✨ Feature, 🎨 Html&css

#29 Feat: tailwindCSS 커스텀 플러그인 (Input, Button) 및 공통 컴포넌트 작성
  package-lock.json
  package.json
  plugins/buttonPlugin.js
  plugins/inputPlugin.js
  src/assets/images/success.svg
  src/assets/images/warning.svg
  src/components/common/CustomInput.tsx
  src/components/common/index.ts
  tailwind.config.js
Labels: ✨ Feature

#32 [Feat] 회원 탈퇴 페이지 작성
  src/assets/images/delete-account/cryingDog.svg
  src/assets/images/delete-account/garbage.svg
  src/pages/DeleteAccount.tsx
  src/pages/index.tsx
  src/router.tsx
Labels: ✨ Feature, 🎨 Html&css

#35 [Feat] 로그인 완료 페이지 컴포넌트 추가
  package-lock.json
  package.json
  src/assets/images/login/smallDog.svg
  src/components/login/Success.tsx
  src/components/login/index.tsx
  src/hooks/useLoginForm.ts
  src/pages/Login.tsx
Labels: ✨ Feature, 🎨 Html&css

#36 [Feat] 도와줘 멍멍 작성 페이지 구현
  package-lock.json
  package.json
  plugins/inputPlugin.js
  src/components/common/DogSelector.tsx
  src/components/common/TimeInput.tsx
  src/components/common/index.ts
  src/components/sos/forms/BasicInfoSection.tsx
  src/components/sos/forms/DateTimeSection.tsx
  src/components/sos/forms/PaymentInput.tsx
  src/components/sos/forms/PaymentSection.tsx
  src/components/sos/forms/PaymentTypeSelect.tsx
  src/components/sos/index.ts
  src/hooks/useSosForm.ts
  src/pages/SOS.tsx
  src/pages/SOSWrite.tsx
  src/types/Sos.d.ts
  src/utils/dateUtils.ts
  src/utils/index.ts
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&css

#39 [Feat] 커스텀 SelectBox 컴포넌트 구현
  plugins/inputPlugin.js
  src/assets/images/bottomArrow.svg
  src/components/common/CustomInput.tsx
  src/components/common/SelectBox.tsx
  src/components/common/index.ts
  src/hooks/index.ts
  src/hooks/useSelectBox.ts
  src/layouts/BottomNav.tsx
  src/layouts/index.tsx
  tailwind.config.js
Labels: ✨ Feature

#40 [Style] 로그인, 임시 비밀번호 발급, 비밀번호 변경 페이지 스타일 변경
  package-lock.json
  src/components/forgot-password/Success.tsx
  src/hooks/useChangePasswordForm.ts
  src/hooks/useForgotPasswordForm.ts
  src/hooks/useLoginForm.ts
  src/pages/ChangePassword.tsx
  src/pages/ForgotPassword.tsx
  src/pages/Login.tsx
Labels: 🎨 Html&css

#42 [Feat] 비밀번호 보기 버튼 추가
  src/assets/images/change-password/eye.svg
  src/components/common/CustomInput.tsx
  src/pages/ChangePassword.tsx
Labels: ✨ Feature, 🎨 Html&css

#43 [Feat] 매칭 페이지 및 기능 구현
  package-lock.json
  package.json
  src/assets/images/arrow/arrowBottom.svg
  src/assets/images/arrow/arrowRight.svg
  src/assets/images/dogs/dogLarge.svg
  src/assets/images/dogs/dogMiddle.svg
  src/assets/images/dogs/dogSmall.svg
  src/assets/images/match/graph.svg
  src/assets/images/match/heart.svg
  src/assets/images/match/matchIntro.svg
  src/assets/images/match/matchIntroBtn.svg
  src/assets/images/match/pawStamp.svg
  src/assets/images/match/plus.svg
  src/assets/images/profile/profile1.svg
  src/assets/images/profile/profile2.svg
  src/assets/images/profile/profile3.svg
  src/components/common/SelectBox.tsx
  src/components/match/FetchMoreCard.tsx
  src/components/match/IntroMatch.tsx
  src/components/match/MatchCard.tsx
  src/components/match/index.ts
  src/layouts/Header.tsx
  src/pages/Match.tsx
  src/router.tsx
  src/stores/index.ts
  src/stores/useMatchStore.ts
  src/types/match.d.ts
Labels: ✨ Feature, 🎨 Html&css

#48 [Feat] 커스텀 toast 작성
  src/components/common/CustomToast.tsx
  src/components/common/index.ts
  src/hooks/useCustomToast.ts
  src/router.tsx
Labels: ✨ Feature

#50 [Feat] 회원가입 페이지 1,2 단계 컴포넌트 작성
  src/components/signup/FirstStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/index.ts
  src/hooks/index.ts
  src/hooks/useSignupForm.ts
  src/pages/ChangePassword.tsx
  src/pages/Signup.tsx
Labels: ✨ Feature, 🎨 Html&css

#52 [Feat] 동물등록 페이지 레이아웃 및 컴포넌트 작성
  src/assets/images/register/registerDog1.svg
  src/assets/images/register/registerDog2.svg
  src/assets/images/register/registerDog3.svg
  src/components/register/RegisterComplete.tsx
  src/components/register/RegisterStep1.tsx
  src/components/register/RegisterStep2.tsx
  src/components/register/RegisterStep3.tsx
  src/components/register/StepIndicator.tsx
  src/components/register/index.ts
  src/pages/Register.tsx
  src/pages/index.tsx
  src/router.tsx
Labels: ✨ Feature, 🎨 Html&css

#57 [Feat] 기본 이미지 선택을 위한 바텀 시트 공통 컴포넌트 작성
  src/assets/images/signup/camera-s.svg
  src/assets/images/signup/profile=1.svg
  src/assets/images/signup/profile=2.svg
  src/assets/images/signup/profile=3.svg
  src/components/common/ImageSelectBox.tsx
  src/components/common/index.ts
Labels: ✨ Feature, 🎨 Html&css

#58 [Feat] 공통 multi-select 컴포넌트 작성
  src/components/common/MultiSelectTag.tsx
  src/components/common/index.ts
  src/utils/index.ts
  src/utils/signup/stringArrayConverter.ts
Labels: ✨ Feature

#59 [Feat] 채팅 API 연결로직 작성 및 채팅 관련 (타입, 전역 스토어, action 매서드)재정의
  .gitignore
  package-lock.json
  package.json
  plugins/buttonPlugin.js
  src/hooks/api/Chat.ts
  src/hooks/api/base.ts
  src/stores/useChatStore.ts
  src/types/chat.d.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#62 💄 로딩 이미지 변경 및 수정
  src/assets/images/loadingDog.svg
  src/components/common/Loading.tsx
Labels: 🎨 Html&css

#63 [Feat] 회원가입 페이지 3,4 단계 컴포넌트 작성
  src/components/common/CustomInput.tsx
  src/components/common/ImageSelectBox.tsx
  src/components/signup/FirstStep.tsx
  src/components/signup/FourthStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/ThirdStep.tsx
  src/components/signup/index.ts
  src/hooks/useSignupForm.ts
  src/pages/Signup.tsx
Labels: ✨ Feature, 🎨 Html&css

#65 [Feat] 회원가입 페이지 동의,완료 단계 컴포넌트 작성
  src/components/common/CustomToggle.tsx
  src/components/common/ImageSelectBox.tsx
  src/components/signup/FourthStep.tsx
  src/components/signup/Success.tsx
  src/components/signup/index.ts
  src/hooks/useSignupForm.ts
  src/pages/Signup.tsx
Labels: ✨ Feature, 🎨 Html&css

#67 [Style] 로그인, 회원가입, 회원탈퇴, 비밀번호 관련 페이지 디자인 수정
  src/components/forgot-password/Success.tsx
  src/components/login/Success.tsx
  src/components/signup/FirstStep.tsx
  src/components/signup/FourthStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/Success.tsx
  src/components/signup/ThirdStep.tsx
  src/pages/ChangePassword.tsx
  src/pages/DeleteAccount.tsx
  src/pages/ForgotPassword.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: 🎨 Html&css

#69 [Style] 로그인과 회원가입 완료 페이지 애니메이션 수정
  src/components/login/Success.tsx
  src/components/signup/Success.tsx
Labels: 🎨 Html&css

#70 [Style] 인트로 페이지 레이아웃 수정
  src/pages/Intro.tsx
Labels: 🎨 Html&css

#72 [Feat] 비밀번호 변경 완료 페이지 작성
  src/components/change-password/Success.tsx
  src/components/change-password/index.ts
  src/components/forgot-password/index.ts
  src/components/forgot-password/index.tsx
  src/components/login/index.ts
  src/hooks/useChangePasswordForm.ts
  src/pages/ChangePassword.tsx
  src/pages/ForgotPassword.tsx
  src/pages/Login.tsx
Labels: ✨ Feature

#74 [Feat] 동물등록번호 조회 기능 구현
  src/components/register/RegisterStep1.tsx
  src/hooks/api/register.ts
  src/hooks/index.ts
  src/pages/Register.tsx
  src/types/register.d.ts
Labels: ✨ Feature, 🎨 Html&css

#76 [Feat] 공통 이미지 선택 바텀 시트 컴포넌트 업그레이드
  src/assets/images/profile/camera-g.svg
  src/assets/images/profile/camera-s.svg
  src/assets/images/signup/profile=1.svg
  src/assets/images/signup/profile=2.svg
  src/assets/images/signup/profile=3.svg
  src/components/common/CustomInput.tsx
  src/components/common/ImageSelectBox.tsx
  src/pages/Signup.tsx
Labels: ✨ Feature, 🎨 Html&css

#78 [Feat] 동물등록 step2 구현
  src/components/register/RegisterStep2.tsx
  src/pages/Register.tsx
  src/types/register.d.ts
Labels: ✨ Feature, 🎨 Html&css

#80 [Feat] 로그인 페이지 api 연동
  src/hooks/api/login.ts
  src/hooks/useLoginForm.ts
  src/pages/Login.tsx
  src/types/login.d.ts
  src/types/user.d.ts
Labels: 📬 API

#81 [Fix] 로그인 로딩 오류 해결
  src/pages/Login.tsx
Labels: 📬 API

#82 [Fix] 로그인 실패 처리 수정
  src/hooks/useLoginForm.ts
Labels: 🐞 BugFix, 📬 API

#87 [Feat] 채팅 관련 페이지 작성 및 로직 수정
  plugins/inputPlugin.js
  public/data/chat.json
  public/data/chatRoom.json
  src/assets/images/arrow/arrowLeft.svg
  src/assets/images/chat/foodBowl.svg
  src/assets/images/chat/puppyWithBowl.svg
  src/assets/images/chat/send.svg
  src/assets/images/common/menuBuger.svg
  src/assets/images/leftArrow.svg
  src/assets/images/menuDots.svg
  src/components/chat-detail/ChatBar.tsx
  src/components/chat-detail/ChatBottom.tsx
  src/components/chat-detail/ChatDetailTitle.tsx
  src/components/chat-detail/ChatTopbar.tsx
  src/components/chat-detail/DateViewer.tsx
  src/components/chat-detail/LeftBubble.tsx
  src/components/chat-detail/MyMessage.tsx
  src/components/chat-detail/OtherMessage.tsx
  src/components/chat-detail/PostGuide.tsx
  src/components/chat-detail/RightBubble.tsx
  src/components/chat-detail/index.ts
  src/components/chat/ChatRoom.tsx
  src/components/chat/ChatRoomSkeleton.tsx
  src/components/chat/NonChatRoom.tsx
  src/components/chat/index.ts
  src/components/common/SelectBox.tsx
  src/hooks/api/Chat.ts
  src/layouts/Header.tsx
  src/layouts/index.tsx
  src/pages/Chat.tsx
  src/pages/ChatDetail.tsx
  src/router.tsx
  src/stores/index.ts
  src/stores/useChatStore.ts
  src/stores/useTitleStore.ts
  src/types/chat.d.ts
  src/utils/chat/getOtherUserForChat.ts
  src/utils/chat/getOtherUserForChatRoom.ts
  src/utils/chat/groupMesagesByDate.ts
  src/utils/chat/index.ts
  src/utils/getDefaultProfileImg.ts
  src/utils/index.ts
  src/utils/utcToCustomDateTime.ts
  vite.config.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css, 🔨 Refactor

#86 [Feat] 회원가입 페이지 이메일 인증코드 api 요청
  src/components/signup/FirstStep.tsx
  src/hooks/api/signup.ts
  src/types/signup.d.ts
Labels: 📬 API

#93 [Feat] 회원가입 페이지 이메일 인증코드 검증 api 연동
  src/components/signup/FirstStep.tsx
  src/components/signup/FourthStep.tsx
  src/hooks/api/signup.ts
  src/hooks/useSignupForm.ts
  src/pages/Signup.tsx
  src/types/signup.d.ts
Labels: 🎨 Html&css, 📬 API

#95 [Feat] 랜딩페이지 레이아웃 작성 및 랭킹 구현
  src/assets/images/intro/arrowRight.svg
  src/components/home/HomeRanking.tsx
  src/components/home/HomeSOS.tsx
  src/components/home/HomeSchedule.tsx
  src/components/home/index.ts
  src/pages/Home.tsx
  src/pages/Ranking.tsx
  src/pages/index.tsx
  src/router.tsx
Labels: ✨ Feature, 🎨 Html&css

#97 [Feat] 회원가입 api 연동
  src/components/common/CustomToast.tsx
  src/components/signup/FirstStep.tsx
  src/components/signup/FourthStep.tsx
  src/components/signup/SecondStep.tsx
  src/components/signup/ThirdStep.tsx
  src/hooks/api/signup.ts
  src/hooks/useSignupForm.ts
  src/pages/Signup.tsx
  src/types/signup.d.ts
Labels: 📬 API

#99 [Feat] GPS 커스텀훅 구현
  src/hooks/useLocation.tsx
  src/types/location.d.ts
Labels: ✨ Feature

#100 [Feat] 프로필 페이지 API 연동
  src/hooks/api/login.ts
  src/hooks/api/profile.ts
  src/hooks/api/signup.ts
  src/hooks/useSignupForm.ts
  src/pages/Profile.tsx
  src/pages/Signup.tsx
  src/router.tsx
  src/types/user.d.ts
Labels: 📬 API

#101 [Feat] 매칭 기능 API 연동 로직 작성
  src/components/match/MatchCard.tsx
  src/components/match/NoMoreCard.tsx
  src/components/match/index.ts
  src/hooks/api/base.ts
  src/hooks/api/match.ts
  src/pages/Match.tsx
  src/stores/useChatStore.ts
  src/stores/useMatchStore.ts
  src/types/baseResponse.d.ts
  src/types/chat.d.ts
  src/types/match.d.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API, 🔨 Refactor

#102 [Feat] 사용자 인증 컴포넌트 작성
  src/components/auth/AuthGard.tsx
  src/components/auth/index.ts
  src/hooks/api/profile.ts
  src/hooks/useLoginForm.ts
  src/types/login.d.ts
  src/types/user.d.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#105 [Feat] 프로필 페이지 프로토타입 퍼블리싱
  src/assets/images/profile/heart.svg
  src/assets/images/profile/lv-5.svg
  src/components/profile/Label.tsx
  src/components/profile/Tag.tsx
  src/components/profile/index.ts
  src/pages/Profile.tsx
Labels: 🎨 Html&css

#106 [Feat] 사용자 인증 컴포넌트 배치
  src/components/auth/AuthGard.tsx
  src/router.tsx
Labels: 🔨 Refactor

#107 [Setting] 개발 서버 환경을 https로 설정
  package-lock.json
  package.json
  vite.config.ts
Labels: ⚙ Setting
